In [1]:
import nfl_data_py as nfl

In [2]:
nfl.see_weekly_cols()

Index(['player_id', 'player_name', 'player_display_name', 'position',
       'position_group', 'headshot_url', 'recent_team', 'season', 'week',
       'season_type', 'completions', 'attempts', 'passing_yards',
       'passing_tds', 'interceptions', 'sacks', 'sack_yards', 'sack_fumbles',
       'sack_fumbles_lost', 'passing_air_yards', 'passing_yards_after_catch',
       'passing_first_downs', 'passing_epa', 'passing_2pt_conversions', 'pacr',
       'dakota', 'carries', 'rushing_yards', 'rushing_tds', 'rushing_fumbles',
       'rushing_fumbles_lost', 'rushing_first_downs', 'rushing_epa',
       'rushing_2pt_conversions', 'receptions', 'targets', 'receiving_yards',
       'receiving_tds', 'receiving_fumbles', 'receiving_fumbles_lost',
       'receiving_air_yards', 'receiving_yards_after_catch',
       'receiving_first_downs', 'receiving_epa', 'receiving_2pt_conversions',
       'racr', 'target_share', 'air_yards_share', 'wopr', 'special_teams_tds',
       'fantasy_points', 'fantasy_points_ppr'],
      dtype='object')

In [7]:
nfl.import_sc_lines([2020])

      season  week away_team home_team     game_id side  line
3584    2020     1       HOU        KC  2020091000  HOU   9.0
3585    2020     1       HOU        KC  2020091000   KC  -9.0
3586    2020     1       SEA       ATL  2020091300  ATL   2.5
3587    2020     1       SEA       ATL  2020091300  SEA  -2.5
3588    2020     1       CLE       BAL  2020091301  BAL  -8.0
...      ...   ...       ...       ...         ...  ...   ...
4087    2020    17       JAX       IND  2021010313  JAX  14.0
4088    2020    17       ARI        LA  2021010314  ARI  -2.5
4089    2020    17       ARI        LA  2021010314   LA   2.5
4090    2020    17       SEA        SF  2021010315  SEA  -6.0
4091    2020    17       SEA        SF  2021010315   SF   6.0

[508 rows x 7 columns]